### ISSUE TITLE
Document fails to save pdf file with svg image.

### ISSUE THREAD

**Issue by bykka** [richard-scryber/scryber.core#113]
**Describe the bug**
Document fails to save pdf file with svg image. It fails with exception:
```
Unhandled exception. Scryber.PDFLayoutException: The layout of component 'panl1' failed. Nullable object must have a value.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Scryber.PDF.Layout.LayoutEngineBase.ApplyRelativeTransformations(PDFLayoutRegion positioned, PDFPositionOptions pos)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(IComponent comp, Style full)
   at Scryber.PDF.Layout.LayoutEngineCanvas.DoLayoutAChild(IComponent comp, Style full)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutChildren()
   at Scryber.PDF.Layout.LayoutEngineCanvas.DoLayoutChildren()
   at Scryber.PDF.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
   at Scryber.PDF.Layout.LayoutEnginePanel.DoLayoutComponent()
   at Scryber.PDF.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
   --- End of inner exception stack trace ---
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(IComponent comp, Style full)
   at Scryber.PDF.Layout.LayoutEngineCanvas.DoLayoutAChild(IComponent comp, Style full)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutChildren()
   at Scryber.PDF.Layout.LayoutEngineCanvas.DoLayoutChildren()
   at Scryber.PDF.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
   at Scryber.PDF.Layout.LayoutEnginePanel.DoLayoutComponent()
   at Scryber.PDF.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(IComponent comp, Style full)
   at Scryber.PDF.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
```

**To Reproduce**
Open test case **Scryber.Core.UnitTests.Html.SVGParsing_Tests.SVGToComponentWithInvariantUnits**
and add the code at the end
```csharp
using var doc = new Document();
        
doc.Pages.Add(new Page
{
    Contents = { svg }
});
doc.SaveAsPDF("svg.pdf", FileMode.Create);
```

**Expected behavior**
Test should past successfully and pdf file should be generated

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1

**Additional context**
It works for commit 8457d2c7e3a7bd3931f71fd8d8d0c19ccb840160 (label 1) but already fails for commit fc3e13395b89f2ff9904f590829e09e743393a63 (label 2)

<img width="1271" alt="image" src="https://github.com/richard-scryber/scryber.core/assets/489997/06e9e013-3595-4212-bff2-42975dae198e">

**Comment by richard-scryber** [comment]
Got it, a minor update to the LayoutEngineBase for a wrong property. Updates the unit test for the svg to output as a document and now works for your chart.

I'll push an updated version now to Nuget. Should be available in the next hour or so.
[SVGInvariant.pdf](https://github.com/richard-scryber/scryber.core/files/12829073/SVGInvariant.pdf)

Thanks for testing I appreciate it. Let me know if it fixes your issue.

**Comment by bykka** [comment]
How did you generate that pdf? Because on my case I see only pie chart but not labels for the segments
<img width="1195" alt="image" src="https://github.com/richard-scryber/scryber.core/assets/489997/cf67f56d-d6d8-4278-844a-fd0fe12abea2">

**Comment by bykka** [comment]
Thank you, now everything works

**Comment by richard-scryber** [comment]
Thank you for your help! :-)
