### ISSUE TITLE
`The initialization of the fonts failed` inside Docker only.

### ISSUE THREAD

**Issue by StanislavChankov** [richard-scryber/scryber.core#62]
**Describe the bug**
Exception occurs, while trying to `doc.SaveAsPDF(stream, true);`
Exception is thrown ONLY, when running inside Docker container, running on Windows/Kestral works as expected.

Code:
```
            try
            {
                using var doc = Document.ParseDocument(pdfTemplate, ParseSourceType.RemoteFile);
                doc.Params["model"] = data;
                var stream = new MemoryStream();
                doc.SaveAsPDF(stream, true); // <= Exception thrown from this line.
                await stream.FlushAsync();
                stream.Position = 0;
                return stream;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error during PDF generation");
                return null;
            }
            ```

Full log from the docker container:
`Scryber.PDFLayoutException: The layout of component 'text2' failed. The initialization of the fonts failed. The type initializer for 'Gdip' threw an exception.
       ---> System.Configuration.ConfigurationErrorsException: The initialization of the fonts failed. The type initializer for 'Gdip' threw an exception.
       ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
       ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
         at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
         at System.Drawing.SafeNativeMethods.Gdip..cctor()
         --- End of inner exception stack trace ---
         at System.Drawing.SafeNativeMethods.Gdip.GdipNewInstalledFontCollection(IntPtr& fontCollection)
         at System.Drawing.Text.InstalledFontCollection..ctor()
         at Scryber.Drawing.PDFFontFactory.LoadSystemFonts()
         at Scryber.Drawing.PDFFontFactory.AssertInitialized()
         --- End of inner exception stack trace ---
         at Scryber.Drawing.PDFFontFactory.AssertInitialized()
         at Scryber.Drawing.PDFFontFactory.GetFontDefinition(String family, FontStyle style, Boolean throwNotFound)
         at Scryber.Components.Document.GetFontResource(PDFFont font, Boolean create, Boolean throwOnNotFound)
         at Scryber.Layout.LayoutEngineText.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineBase.DoLayoutTextComponent(IPDFTextComponent text, Style style)
         --- End of inner exception stack trace ---
         at Scryber.Layout.LayoutEngineBase.DoLayoutTextComponent(IPDFTextComponent text, Style style)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(IPDFComponent comp, Style full)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren()
         at Scryber.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
         at Scryber.Layout.LayoutEnginePanel.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(IPDFComponent comp, Style full)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren()
         at Scryber.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
         at Scryber.Layout.LayoutEnginePanel.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(IPDFComponent comp, Style full)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren()
         at Scryber.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
         at Scryber.Layout.LayoutEnginePanel.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(IPDFComponent comp, Style full)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren(ComponentList children)
         at Scryber.Layout.LayoutEngineBase.DoLayoutChildren()
         at Scryber.Layout.LayoutEnginePanel.DoLayoutBlockComponent(PDFPositionOptions position, PDFColumnOptions columnOptions)
         at Scryber.Layout.LayoutEnginePanel.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineBase.DoLayoutViewPortComponent(IPDFViewPortComponent viewPort, Style style)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(IPDFComponent comp, Style full)
         at Scryber.Layout.LayoutEngineBase.DoLayoutAChild(Component comp)
         at Scryber.Layout.LayoutEnginePage.LayoutPageHeaderAndFooter()
         at Scryber.Layout.LayoutEnginePage.LayoutPageContent()
         at Scryber.Layout.LayoutEnginePage.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineSection.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Layout.LayoutEngineDocument.LayoutPageWithStyle(PageBase pg, Style full)
         at Scryber.Layout.LayoutEngineDocument.LayoutPage(PageBase pg)
         at Scryber.Layout.LayoutEngineDocument.LayoutAllPages()
         at Scryber.Layout.LayoutEngineDocument.DoLayoutComponent()
         at Scryber.Layout.LayoutEngineBase.Layout(PDFLayoutContext context, Style fullstyle)
         at Scryber.Components.Document.RenderToPDF(PDFRenderContext context, PDFWriter writer)
         at Scryber.Components.Document.RenderToPDF(Stream tostream)
         at Scryber.Components.Document.RenderTo(Stream tostream, OutputFormat format)
         at Scryber.Components.Document.SaveAs(Stream stream, Boolean bind, OutputFormat format)
         at Scryber.Components.Document.SaveAsPDF(Stream stream, Boolean bind)`

**To Reproduce**
Run the following code.

**Expected behavior**
The expected result should be the same on Linux container as Windows.

**Desktop (please complete the following information):**
 - Device: Dell
 - OS: Windows 10
 - Docker OS: Linux Debian

**Comment by richard-scryber** [comment]
Hi Stanislav, yeah - I am aware of this, and scurrying away in the background for botnet standard 2.0 and zero references to System.Drawing images and fonts. It is currently in the 'documentation' branch rather than master. 

You might be able to sort something in the docker initialiser, but this article details the issue a bit more. [https://scrybercore.readthedocs.io/en/v1.0.0.20-beta/libgdiplus.html](https://scrybercore.readthedocs.io/en/v1.0.0.20-beta/libgdiplus.html)

If you do solve, then please do post

**Comment by StanislavChankov** [comment]
Yes, we were able to solve it by installing `libgdiplus` in the container.

# Stage 2 - Run the application
..........
COPY --from=publish /app/publish .

**RUN apt-get update && apt-get install -y libgdiplus libc6-dev**

ENTRYPOINT ["dotnet", "Test.dll"]
